title: Bowen Shi
logo: shibowen.jpeg
description: I am a Ph.D. student in the Department of Computer Science and Engineering at Shanghai Jiao Tong University, advised by Prof.[Junni Zou and Prof. Hongkai Xiong. Before that, I obtained my B.E. degree at the School of Software Technology, Dalian University of Technology, 2019. From Sep. 2020 till now, I have been an intern at Huawei Inc., Shanghai, mentored by Dr. Xiaopeng Zhang and Prof. Qi Tian.
theme: jekyll-theme-minimal
